from django.db import models
class HydJobs(models.Model):
    date=models.DateField()
    company=models.CharField(max_length=64)
    title=models.CharField(max_length=64)
    eligibility=models.CharField(max_length=30)
    address=models.CharField(max_length=64)
    email=models.EmailField()
    phonenumber=models.BigIntegerField()
class PuneJobs(models.Model):
    date=models.DateField()
    company=models.CharField(max_length=64)
    title=models.CharField(max_length=64)
    eligibility=models.CharField(max_length=30)
    address=models.CharField(max_length=64)
    email=models.EmailField()
    phonenumber=models.BigIntegerField()
class BangJobs(models.Model):
    date=models.DateField()
    company=models.CharField(max_length=64)
    title=models.CharField(max_length=64)
    eligibility=models.CharField(max_length=30)
    address=models.CharField(max_length=64)
    email=models.EmailField()
    phonenumber=models.BigIntegerField()
