# Generated by Django 5.1 on 2025-02-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('eligibility', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.BigIntegerField(max_length=30)),
            ],
        ),
    ]
