# Generated by Django 5.1 on 2025-02-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
