# Generated by Django 5.1 on 2025-02-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_hydjobs_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydjobs',
            old_name='adress',
            new_name='address',
        ),
    ]
